#!/bin/sh

if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=$(git hash-object -t tree /dev/null)
fi

# Redirect output to stderr.
exec 1>&2

# Cross platform projects tend to avoid non-ASCII filenames; prevent
# them from being added to the repository. We exploit the fact that the
# printable range starts at the space character and ends with tilde.
#
# Note that the use of brackets around a tr range is ok here, (it's
# even required, for portability to Solaris 10's /usr/bin/tr), since
# the square bracket bytes happen to fall in the designated range.
if test $(git diff --cached --name-only --diff-filter=A -z $against |
	      LC_ALL=C tr -d '[ -~]\0' | wc -c) != 0
then
    cat <<\EOF
Error: Attempt to add a non-ASCII file name.

This can cause problems if you want to work with people on other platforms.

To be portable it is advisable to rename the file.
EOF
	exit 1
fi

if mill show __.publishVersion 2>/dev/null | jq --raw-output '.[]' | \grep -E '[^0-9.]'
then
  cat <<\EOF
Error: Version number contains unexpected characters.

Sometimes a 'g' will sneak in there, (see version 0.2g.0), please double-check the publishVersion in build.sc
EOF
  exit 1
fi

mill __.compile + \
     __.test + \
     __.fix --check + \
     __.checkFormat
