name: Continuous Integration

on: issue_comment  

permissions:
  contents: read

jobs:
  build:
    name: Verify PR
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '/verify') }}
    runs-on: ubuntu-latest

    steps:
    - uses: jodersky/setup-mill@master
      with:
        mill-version: 0.10.5
    - name: Compile
      run: mill __.compile
    - name: Test
      run: mill __.test
    - name: Format
      run: mill __.checkFormat
